:repository-owner: arduino-libraries
:repository-name: MIDIUSB

= {repository-name} Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

== This fork ==

**DISCLAIMER**: This is a FORK of the original library with additional methods that allow for checking whether the USB host is receiving data or not. In the original implementation a call to `write()`, and by extension `sendMIDI()` would cause the program to block. I aimed to expose a couple other functions that should make handling this possible.

For now, it only works with https://github.com/Levi--G/USBLibrarySTM32[Levi--G's USB API for STM32] on an STM32F103. Some methods depend on functions declared by Levi--G that are not available for other USB APIs. If I figure out how to make it work without depending on their implementation-specific libraries (possibly via some defined macros), I'll update the library accordingly. For now, I didn't have the need or time, so it will only work with that library.

This fork's additions:

* `bool MIDIUSB::availableTx()` - returns whether the USB host is receiving sent data, will turn `false` after the first unread packet. (works only with `Levi--G's USB API for STM32`)
* `void MIDIUSB::sendMIDIQuick(midiEventPacket_t)` - replaces `write()` call in the original method with `writeQuick()`. (works only with `Levi--G's USB API for STM32`)
* `size_t MIDIUSB::writeQuick(const uint8_t* buffer, size_t size)` - writes data to the USB endpoint but uses Levi--G's `USB_SendQuick()` instead of the original blocking `USB_Send()`. Combined with `MIDIUSB::availableTx()` you can prevent blocking. You'll achieve the desired non-blocking behavior if you prevent USB flushing on subsequent `USB_SendQuick` calls. (works only with `Levi--G's USB API for STM32`)
* `uint8_t MIDIUSB::getMIDIRxEndpoint()` - returns the MIDI RX USB endpoint.
* `uint8_t MIDIUSB::getMIDITxEndpoint()` - returns the MIDI TX USB endpoint. Comes in handy for some USB API methods.

== Description ==

This library allows an Arduino board with USB capabilities to act as a MIDI instrument over USB. The library is based on PluggableUSB, so is only compatible with Arduino IDE 1.6.6 and newer.

Furthermore, since PluggableUSB only targets boards with native USB capabilities, this library only supports these boards (eg. Leonardo, Micro, Due, Zero and so on)

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/{repository-name}

== Test procedure (Linux) ==

Load the correct driver (`sudo modprobe snd_seq_midi`)

Flash the board with `MIDIUSB_loop` example, then execute `aseqdump -l`; the output will be something similar to
```bash
Port    Client name                      Port name
  0:0    System                           Timer
  0:1    System                           Announce
 14:0    Midi Through                     Midi Through Port-0
 20:0    Arduino Micro                    Arduino Micro MIDI 1
```
Port `20` is the one we'll use in the following examples.

Start `fluidsynth` inside a shell with a soundbank 
```bash
fluidsynth --server --audio-driver=alsa -o audio.alsa.device=hw:0 ~/Synth.SF2
```

In another shell, execute 
```bash
aconnect 20 128
```
to connect our MIDI device with fluidsynth

Then, execute
```bash
aplaymidi  --port=20:0 ~/some_midi_file.mid
```
and the file will be played after a complete roundtrip to the board.
